### ISSUE TITLE
Narea data?

### ISSUE THREAD

**Issue by stineb** [MESI-organization/mesi-db#3]
There doesn't seem to be any data for nitrogen per unit leaf area (N_area) in MESI.
```r
library(tidyverse)
df <- read_csv("data/mesi_main.csv")
df %>% 
    filter(str_detect(response, "narea")) %>% 
    group_by(exp) %>% 
    summarise(n = sum(rep_c))
```
Am I missing anything? If not, is there a reason for not including such data?
@KevinVanSundert 
Thanks! 
beni

**Comment by KevinVanSundert** [comment]
Fixed: leaf_n now specified as leaf_n_mass vs leaf_n_area in the latest version.
